name: Build

on:
  push:
    branches:
      - wip

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  
  NUGET_FEED: https://api.nuget.org/v3/index.json

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore --verbosity normal
    - name: Build
      run: dotnet build --configuration Release --no-restore --verbosity normal
    - name: Test
      run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
